### PR TITLE
Adapt for iOS devices

### PR DESCRIPTION
**Pull request by sikmir**
Optimized for web application:
- hide Safari UI components
- minimize the status bar
- add apple-touch-icon.png (57 x 57, 8-bit/color RGBA, created from favicon.ico)

@wladich Could you provide icon in higher resolution or in vector format, if any?

For more details, see [Configuring Web Applications](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html).

### CODE REVIEW

**Comment by sikmir** [comment]
@wladich What about this PR, do you have any objections? It's really very convenient for those who use nakarte as an iOS application.

**Comment by wladich** [comment]
У меня нет девайса с ios, чтобы посмотреть, что получается. Попробую не забыть посмотреть у кого-нибудь из знакомых, у кого есть айфон, но не раньше, чем через неделю

**Comment by sikmir** [comment]
OK, it's better to try on iPad. iPhone is too small for that.
Just in case, small how-to:
1. Open nakarte.tk in Safari.
2. Click "Add to Home Screen", "Add".
3. Close Safari, open your new web app.

**Comment by sikmir** [comment]
Currently I use self-hosted nakarte with some adjustments (including this PR) for personal needs. So I'm going to close this PR.

**Pull request closed without merging**
