### PR TITLE
Add 'Show My Location' control

### PR DESCRIPTION
**Pull request by sikmir**
It was inconvenient that we had to Zoom&Pan every time to get into desired location outside of default one (Moscow). Now this can be done in the usual way, by geolocation.

screenshot
Dependencies:
* [domoritz/leaflet-locatecontrol](https://github.com/domoritz/leaflet-locatecontrol) (MIT)
* [Font Awesome](http://fontawesome.io/) (webfont: SIL OFL 1.1, css: MIT)

### CODE REVIEW

**Comment by wladich** [comment]
Does not work in Chrome without https (works only on localhost): http://stage.nakarte.tk
Migration to HTTPS is not planned.

**Comment by sikmir** [comment]
@wladich But it works in other browsers (Firefox, etc). Why we should stick with Chrome?

**Comment by wladich** [comment]
It works only in Firefox (18% of users) and maybe in IE (~5%)
Not even in Safari: https://stackoverflow.com/questions/39633313/got-an-error-when-trying-to-get-the-geolocation-in-safari-on-ios-10.

I don`t like features which are not working for ~75% of users (according to browser usage from access logs)

**Comment by wladich** [comment]
Automatic map positioning (without tracking) can be done via geoip.
Maybe someday...

**Comment by sikmir** [comment]
OK, so there are two ways here:
- use https
- use geoip

The 1st one is much more easy:
- at no cost (Let's Encrypt)
- with minimum efforts (if you are not on shared hosting)

Do you object to using https anyway? In that case, I'll try to implement with geoip.

**Comment by wladich** [comment]
Migration to https requires testing in all major browsers that all layers are
a) displayed
b) downloaded for pdf and jnx
which is long and boring. 

Post at stackoverflow earlier in thread states that http-loaded map layers are not shown in Safari on https-loaded pages. 

So, it is not that easy

**Comment by sikmir** [comment]
What about Safari I've just checked with Safari 10.1.1 - no problems with displaying http-loaded tiles on https-loaded page.
Anyway, if testing is only obstacle on that way, I can help with it. Let's say on https://stage.nakarte.tk.
There are not so many options:
- browsers and major versions (Chrome, Firefox, Safari, others from access log)
- maps (http-, https-loaded)
- downloads (pdf, jnx)
- what else...

**Comment by sikmir** [comment]
Some points against geoip-based location:
- incorrect if VPN is used
- inaccurate (even though device has GPS unit)

**Comment by sikmir** [comment]
Implemented in #65.

**Pull request closed without merging**
